FROM ubuntu:latest
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install git
RUN apt-get -y install build-essential
RUN apt-get -y install clang
RUN apt-get -y install clang-format
RUN apt-get -y install cmake
RUN apt-get -y install clang-tidy
